apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp2
spec:
  selector:
    matchLabels:
      app: myapp2
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp2
    spec:
      containers:
      - name: myapp2
        image: hashicorp/http-echo:0.2.3
        args:
          - "-text=Hello from Kubernetes!"
        imagePullPolicy: Always
        ports:
        - containerPort: 5678